### ISSUE TITLE
Style of note not the same on all webpages

### ISSUE THREAD

**Issue by hibroseph** [hibroseph/docamatic#1]
The font of the text changes and size of the icons. This is not ideal

**Expected behavior:**
Notes look exactly the same on all pages

**Current behavior**
A note on stackoverflow
![image](https://user-images.githubusercontent.com/28901411/58065332-91760680-7b42-11e9-8447-d4892fee702c.png)

A note on wikipedia 
![image](https://user-images.githubusercontent.com/28901411/58065382-c3876880-7b42-11e9-9c6f-8a506d822c95.png)

Notice the note title moved down a little and the size of the icons are different.

**Comment by hibroseph** [comment]
Also this is on github 
![image](https://user-images.githubusercontent.com/28901411/58066523-f2074280-7b46-11e9-9857-5bae5dd59fee.png)

**Comment by adlythebaud** [comment]
Wondering I should make all notes use the same css file in the manifest here:
![image](https://user-images.githubusercontent.com/24305066/58223184-f01fb980-7cd5-11e9-8fcb-5edd73e97324.png)

**Comment by hibroseph** [comment]
Maybe. I actually didn't think around messing around with the manifest. Try it and tell me what happens haha.

**Comment by hibroseph** [comment]
@adlythebaud Where are you at on this? I am just asking because I want to refactor all the code in the note to make it a lot more modular to make it more testable and my refactoring will conflict directly with what you are working on.

**Comment by adlythebaud** [comment]
I’m not very far, so you can go ahead and refactor. I can make the styling modular as well so I don’t think it’ll be a big issue. Just tell me how you want to modularize the note and I’ll code similarly.

**Comment by hibroseph** [comment]
Okay I already started. Essentially I am going to use a lot more folders, and move all the relevant code into the folders. So for every component I think I will make a separate folder and just import those folders. 

So for example There is a Block Color Picker, so I made a Note folder and a Color Picker folder and there I am putting the CSS and javascript. 

You can take a current look at my branch refactoring code and that will kinda show it. 


I am going to be adding testing and apparently the smaller you make your components, the easier they are to test so yeah. I guess I'm going to try to make them as small as possible

**Comment by adlythebaud** [comment]
I think that’s a great idea. If we go that route we can force every component that has its own style sheet to use only its own style sheet, and not its parent. It’ll be a little tricky but doable.

**Comment by hibroseph** [comment]
@adlythebaud also I figured out after 2 hours that if you do use basic css sheets (which is what I am starting to use), you do have to include it in the manifest.json file css section.

**Comment by adlythebaud** [comment]
That’s what I was thinking. Because they need to be bundled and used by the whole app. I read that there’s a way to have stylesheets for each component and that they can reuse class names and ID names without conflict. I think we’ll have to do something like that for this. I’ll post a link to it on this issue when I get home.

**Comment by hibroseph** [comment]
Is it called Styled components? I think that's the idea behind those. Reuse
the code

**Comment by hibroseph** [comment]
Great progress was made on this introducing the shadow root. Closing for now until we find a specific page where the note style is not the same
